[package]
name = "static_object"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_object_derive = { path = "static_object_derive" }
tokio = { version = "1.21.0", features = ["full"] }