name: "Init environment"
description: ""
inputs:
  requireCache:
    description: "require cache or not"
    required: false
    default: "true"
  rust:
    description: "init rust toolchain"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: install Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      if: inputs.rust == 'true'
      with:
        toolchain: stable

    - name: do cache
      uses: ./.github/actions/doCache
      if: inputs.requireCache == 'true'

    - name: install dependencies (ubuntu only)
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: (matrix.platform == 'ubuntu-latest') && (inputs.rust == 'true')
      with:
        packages: libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
        version: 1.0

    - name: yarn install
      run: yarn install
      shell: "bash"

    - name: mkdir dist
      run: mkdir dist
      shell: "bash"
