name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: init environment
        uses: ./.github/actions/initEnvironment

      - name: before build
        if: success()
        run: node scripts/beforeBuild.mjs

      - name: build
        if: success()
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: node scripts/build.mjs

      - name: copyArtifacts.mjs
        if: success()
        run: node scripts/copyArtifacts.mjs

      - name: upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out/*
