name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: init environment
        uses: ./.github/actions/initEnvironment
        with:
          rust: "false"
          requireCache: "false"

      - uses: actions/download-artifact@v3
        with:
          path: .

      - name: generate update info
        run: node scripts/genUpdateInfo.mjs

      - name: create release
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/createRelease.js')
            return await script({github, context})
