name: Lint

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: init environment
        uses: ./.github/actions/initEnvironment

      #      - name: test build frontend
      #        if: success()
      #        run: yarn build

      - name: backend lint
        if: success()
        run: node scripts/backendLint.mjs

      - name: upload target
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: target-${{ runner.os }}
          path: src-tauri/target
