name: Lint

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: init environment
        uses: ./.github/actions/initEnvironment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: lint
        if: success()
        run: cargo make ci-lint
