name: Build and Release

# Controls when the workflow will run
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"


jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cache cargo and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./src-tauri/target
          key: ${{ runner.os }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: before build
        if: success()
        run: node scripts/beforeBuild.mjs

      - name: build
        if: success()
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: node scripts/build.mjs

      - name: renameArtifacts.mjs
        if: success()
        run: node scripts/renameArtifacts.mjs
